DROP DATABASE IF EXISTS burgers_db;

CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burger(
    Id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(40),
    devoured BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY(Id)
);